In [1]:
%pylab inline
import time
import numpy as np
from segbench import csaAssign, correspondPixels, matchEdgeMaps2D, matchEdgeMaps3D

Populating the interactive namespace from numpy and matplotlib


In [2]:
data = np.array([[1, 4, 3],
    [2, 5, 3],
    [3, 6, 3],
    [1, 5, 1],
    [2, 6, 1],
    [3, 4, 5]])
n = 6
e1 = csaAssign(n,data)
print e1

[[ 1.  5.  1.]
 [ 2.  6.  1.]
 [ 3.  4.  5.]]


In [3]:
n = 1000
dg = np.random.rand(n,n)>.5
m = np.sum(dg.flat)
i = np.array(dg.ravel().nonzero()).astype(float)
g1 = 1+np.floor(np.divide(i,n))
g2 = (1+np.floor(np.divide(i,n)),
     1+ np.mod(i,n)+n,
     1+np.floor(np.random.rand(1,m))*1000)
g2 = np.array(np.vstack(g2)).T
t = time.time()
e2 = csaAssign(n*2,g2)
print '{:.3e}s'.format(time.time() - t)

8.563e-02s


In [5]:
esum = np.sum(e2,axis=0)
if not all(esum[0:2]==(n*(n+1)/2,n*(n+1)/2+n*n)): raise ValueError("bug")
if not np.sum(esum[0:2])==(2*n*(2*n+1)/2): raise ValueError("bug")
print n,m, e2[3][:]

1000 499745 [  4.00000000e+00   1.00100000e+03   1.00000000e+00]


In [5]:
thres = .5
n = 100
for n in np.round(np.logspace(0,2,10)).astype(int):
    for thresh in np.linspace(0,1,10):
        print 'n={:d} thresh={:1.2e}'.format(n,thresh),
        bmap1 = (np.random.rand(n,n)>thres).astype(float)
        bmap2 = (np.random.rand(n,n)>thres).astype(float)

        match1 = zeros_like(bmap1)
        match2 = zeros_like(bmap2)
        t = time.time()
        cost,oc = correspondPixels(bmap1,bmap2,match1,match2,.005)
        print '{:1.2e}s'.format(time.time() - t),
        npix = len(bmap1.nonzero()[0]) + len(bmap2.nonzero()[0])
        ncor = len(match1.nonzero()[0]) + len(match1.nonzero()[0])
        nout = len(((bmap1>0)&(match1==0)).nonzero()[0]) + len(((bmap2>0)&(match2==0)).nonzero()[0])
        print npix,ncor,nout
        if ncor+nout!=npix: raise ValueError("bug")
        match1f = match1.ravel()
        idx1 = match1f.astype(int)
        a1 = match1f.nonzero()[0]
        a2 = match1f[idx1.nonzero()[0]].ravel()
        a = vstack((a1,a2)).T


        match2f = match2.ravel()
        idx2 = match2f.astype(int)
        b1 = match2f.nonzero()[0]
        b2 = match2f[idx2.nonzero()[0]].ravel()
        b = vstack((b2,b1)).T
        b = b[b[:,0].argsort(),]
        if sum(a-b): raise ValueError("bug")

n=1 thresh=0.00e+00 4.83e-03s 1 0 1
n=1 thresh=1.11e-01 1.79e-05s 1 0 1
n=1 thresh=2.22e-01 4.41e-05s 2 2 0
n=1 thresh=3.33e-01 9.06e-06s 0 0 0
n=1 thresh=4.44e-01 1.10e-05s 0 0 0
n=1 thresh=5.56e-01 3.50e-05s 2 2 0
n=1 thresh=6.67e-01 7.87e-06s 1 0 1
n=1 thresh=7.78e-01 1.00e-05s 1 0 1
n=1 thresh=8.89e-01 6.91e-06s 0 0 0
n=1 thresh=1.00e+00 9.06e-06s 1 0 1
n=2 thresh=0.00e+00 3.91e-05s 5 4 1
n=2 thresh=1.11e-01 8.11e-06s 3 0 3
n=2 thresh=2.22e-01 5.70e-05s 7 6 1
n=2 thresh=3.33e-01 3.91e-05s 6 4 2
n=2 thresh=4.44e-01 7.30e-05s 5 4 1
n=2 thresh=5.56e-01 7.10e-05s 4 2 2
n=2 thresh=6.67e-01 6.20e-05s 4 2 2
n=2 thresh=7.78e-01 4.70e-05s 6 4 2
n=2 thresh=8.89e-01 1.41e-05s 3 0 3
n=2 thresh=1.00e+00 4.79e-05s 5 2 3
n=3 thresh=0.00e+00 5.01e-05s 11 6 5
n=3 thresh=1.11e-01 3.00e-05s 6 2 4
n=3 thresh=2.22e-01 4.39e-05s 11 6 5
n=3 thresh=3.33e-01 4.60e-05s 10 6 4
n=3 thresh=4.44e-01 3.29e-05s 6 2 4
n=3 thresh=5.56e-01 3.70e-05s 10 4 6
n=3 thresh=6.67e-01 6.89e-05s 13 8 5
n=3 thresh=7.78e-01 6.5

In [12]:
thres = .5
n = 100
for n in np.round(np.logspace(0,2,10)).astype(int):
    for thresh in np.linspace(0,1,2):
        print 'n={:d} thresh={:1.2e}'.format(n,thresh),
        bmap1 = (np.random.rand(n,n)>thresh).astype(float)
        bmap2 = (np.random.rand(n,n)>thresh).astype(float)

        match1 = zeros_like(bmap1)
        match2 = zeros_like(bmap2)
        t = time.time()
        cost = matchEdgeMaps2D(bmap1,bmap2,match1,match2,.005,100)
        print '{:1.2e}s'.format(time.time() - t),
        npix = len(bmap1.nonzero()[0]) + len(bmap2.nonzero()[0])
        ncor = len(match1.nonzero()[0]) + len(match1.nonzero()[0])
        nout = len(((bmap1>0)&(match1==0)).nonzero()[0]) + len(((bmap2>0)&(match2==0)).nonzero()[0])
        print ncor,'+',nout,'=',ncor+nout,'==',npix
        if ncor+nout!=npix: raise ValueError("bug")
        match1f = match1.ravel()
        idx1 = match1f.astype(int)
        a1 = match1f.nonzero()[0]
        a2 = match1f[idx1.nonzero()[0]].ravel()
        a = vstack((a1,a2)).T


        match2f = match2.ravel()
        idx2 = match2f.astype(int)
        b1 = match2f.nonzero()[0]
        b2 = match2f[idx2.nonzero()[0]].ravel()
        b = vstack((b2,b1)).T
        b = b[b[:,0].argsort(),]
        if sum(a-b): raise ValueError("bug")

n=1 thresh=0.00e+00 1.81e-05s 0 + 1 = 1 == 1
n=1 thresh=1.11e-01 5.60e-05s 2 + 0 = 2 == 2
n=1 thresh=2.22e-01 1.31e-05s 0 + 1 = 1 == 1
n=1 thresh=3.33e-01 5.41e-05s 2 + 0 = 2 == 2
n=1 thresh=4.44e-01 1.10e-05s 0 + 0 = 0 == 0
n=1 thresh=5.56e-01 1.22e-05s 0 + 0 = 0 == 0
n=1 thresh=6.67e-01 1.00e-05s 0 + 1 = 1 == 1
n=1 thresh=7.78e-01 1.19e-05s 0 + 1 = 1 == 1
n=1 thresh=8.89e-01 5.39e-05s 2 + 0 = 2 == 2
n=1 thresh=1.00e+00 1.10e-05s 0 + 1 = 1 == 1
n=2 thresh=0.00e+00 6.39e-05s 4 + 1 = 5 == 5
n=2 thresh=1.11e-01 5.60e-05s 4 + 1 = 5 == 5
n=2 thresh=2.22e-01 6.22e-05s 4 + 2 = 6 == 6
n=2 thresh=3.33e-01 3.98e-05s 4 + 2 = 6 == 6
n=2 thresh=4.44e-01 4.10e-05s 4 + 2 = 6 == 6
n=2 thresh=5.56e-01 3.79e-05s 4 + 2 = 6 == 6
n=2 thresh=6.67e-01 8.11e-06s 0 + 4 = 4 == 4
n=2 thresh=7.78e-01 3.41e-05s 2 + 2 = 4 == 4
n=2 thresh=8.89e-01 7.15e-06s 0 + 4 = 4 == 4
n=2 thresh=1.00e+00 5.96e-06s 0 + 3 = 3 == 3
n=3 thresh=0.00e+00 8.11e-06s 0 + 3 = 3 == 3
n=3 thresh=1.11e-01 3.79e-05s 2 + 5 = 7 == 7
n=3 thresh

In [1]:
%pylab inline
import time
import numpy as np
from segbench import csaAssign, correspondPixels, matchEdgeMaps2D, matchEdgeMaps3D2
for n in np.round(np.logspace(0,6,4,base=2)).astype(int):
    for thresh in np.linspace(.1,.8,4):
        print 'n={:d} thresh={:1.2e}'.format(n,thresh),
        bmap1 = (np.random.rand(n,n,n)>thresh).astype(float)
        bmap2 = (np.random.rand(n,n,n)>thresh).astype(float)

#         match1 = zeros_like(bmap1)
#         match2 = zeros_like(bmap2)
        t = time.time()
        cost,match1,match2 = matchEdgeMaps3D2(bmap1,bmap2,.000005,100)
        print '{:1.4f}s'.format(time.time() - t),
        npix = len(bmap1.nonzero()[0]) + len(bmap2.nonzero()[0])
        ncor = len(match1.nonzero()[0]) + len(match1.nonzero()[0])
        nout = len(((bmap1>0)&(match1==0)).nonzero()[0]) + len(((bmap2>0)&(match2==0)).nonzero()[0])
        print ncor,'+',nout,'=',ncor+nout,'==',npix
        if ncor+nout!=npix: raise ValueError("bug")
        match1f = match1.ravel()
        idx1 = match1f.astype(int)
        a1 = match1f.nonzero()[0]
        a2 = match1f[idx1.nonzero()[0]].ravel()
        a = vstack((a1,a2)).T


        match2f = match2.ravel()
        idx2 = match2f.astype(int)
        b1 = match2f.nonzero()[0]
        b2 = match2f[idx2.nonzero()[0]].ravel()
        b = vstack((b2,b1)).T
        b = b[b[:,0].argsort(),]
        if sum(a-b): raise ValueError("bug")

Populating the interactive namespace from numpy and matplotlib
n=1 thresh=1.00e-01 0.0001s 2 + 0 = 2 == 2
n=1 thresh=3.33e-01 0.0001s 2 + 0 = 2 == 2
n=1 thresh=5.67e-01 0.0000s 0 + 1 = 1 == 1
n=1 thresh=8.00e-01 0.0000s 0 + 1 = 1 == 1
n=4 thresh=1.00e-01 0.0011s 106 + 10 = 116 == 116
n=4 thresh=3.33e-01 0.0006s 56 + 30 = 86 == 86
n=4 thresh=5.67e-01 0.0002s 20 + 30 = 50 == 50
n=4 thresh=8.00e-01 0.0001s 6 + 17 = 23 == 23
n=16 thresh=1.00e-01 0.1794s 6626 + 750 = 7376 == 7376
n=16 thresh=3.33e-01 0.0877s 3554 + 1842 = 5396 == 5396
n=16 thresh=5.67e-01 0.0372s 1600 + 2034 = 3634 == 3634
n=16 thresh=8.00e-01 0.0062s 364 + 1342 = 1706 == 1706
n=64 thresh=1.00e-01 51.2662s 423894 + 48141 = 472035 == 472035
n=64 thresh=3.33e-01 23.1552s 231730 + 117329 = 349059 == 349059
n=64 thresh=5.67e-01 5.5559s 98024 + 129143 = 227167 == 227167
n=64 thresh=8.00e-01 0.6521s 20674 + 83788 = 104462 == 104462
